### ISSUE TITLE
Create certificates using certbot task fails

### ISSUE THREAD

**Issue by enricostano** [openfoodfoundation/ofn-install#105]
### WHAT
I'm not sure since when, provisioning a server that has already been provisioned before will fail running the task [Create certificates using certbot](https://github.com/openfoodfoundation/ofn-install/blob/master/roles/cert/tasks/main.yml#L3) due to missing permissions.

### TODO
 - [ ] Check if this happen also to brand new servers
 - [ ] Check if this task is correct / needed / idempotent enough
 - [ ] Check if something changed in `certbot`

### LOGS
```
TASK [cert : Create certificates using certbot] ***************************************************************************************
task path: /home/enrico/dev/ofn/ofn-install/roles/cert/tasks/main.yml:3
Friday 12 January 2018  12:03:06 +0100 (0:00:01.967)       0:05:06.602 ******** 
Using module file /usr/lib/python2.7/site-packages/ansible/modules/commands/command.py
<212.47.234.234> ESTABLISH SSH CONNECTION FOR USER: ofn-admin
<212.47.234.234> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ofn-admin -o ConnectTimeout=10 -o ControlPath=/home/enrico/.ansible/cp/%h-%r 212.47.234.234 '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<212.47.234.234> (0, '/home/ofn-admin\n', '')
<212.47.234.234> ESTABLISH SSH CONNECTION FOR USER: ofn-admin
<212.47.234.234> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ofn-admin -o ConnectTimeout=10 -o ControlPath=/home/enrico/.ansible/cp/%h-%r 212.47.234.234 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/ofn-admin/.ansible/tmp/ansible-tmp-1515754986.93-96984067789608 `" && echo ansible-tmp-1515754986.93-96984067789608="` echo /home/ofn-admin/.ansible/tmp/ansible-tmp-1515754986.93-96984067789608 `" ) && sleep 0'"'"''
<212.47.234.234> (0, 'ansible-tmp-1515754986.93-96984067789608=/home/ofn-admin/.ansible/tmp/ansible-tmp-1515754986.93-96984067789608\n', '')
<212.47.234.234> PUT /tmp/tmpl0vKao TO /home/ofn-admin/.ansible/tmp/ansible-tmp-1515754986.93-96984067789608/command.py
<212.47.234.234> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ofn-admin -o ConnectTimeout=10 -o ControlPath=/home/enrico/.ansible/cp/%h-%r '[212.47.234.234]'
<212.47.234.234> (0, 'sftp> put /tmp/tmpl0vKao /home/ofn-admin/.ansible/tmp/ansible-tmp-1515754986.93-96984067789608/command.py\n', '')
<212.47.234.234> ESTABLISH SSH CONNECTION FOR USER: ofn-admin
<212.47.234.234> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ofn-admin -o ConnectTimeout=10 -o ControlPath=/home/enrico/.ansible/cp/%h-%r 212.47.234.234 '/bin/sh -c '"'"'chmod u+x /home/ofn-admin/.ansible/tmp/ansible-tmp-1515754986.93-96984067789608/ /home/ofn-admin/.ansible/tmp/ansible-tmp-1515754986.93-96984067789608/command.py && sleep 0'"'"''
<212.47.234.234> (0, '', '')
<212.47.234.234> ESTABLISH SSH CONNECTION FOR USER: ofn-admin
<212.47.234.234> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ofn-admin -o ConnectTimeout=10 -o ControlPath=/home/enrico/.ansible/cp/%h-%r -tt 212.47.234.234 '/bin/sh -c '"'"'/usr/bin/python /home/ofn-admin/.ansible/tmp/ansible-tmp-1515754986.93-96984067789608/command.py; rm -rf "/home/ofn-admin/.ansible/tmp/ansible-tmp-1515754986.93-96984067789608/" > /dev/null 2>&1 && sleep 0'"'"''
<212.47.234.234> (0, '\r\n{"changed": true, "end": "2018-01-12 11:03:15.698693", "stdout": "Requesting to rerun /opt/certbot/certbot-auto with root privileges...", "cmd": ["/opt/certbot/certbot-auto", "certonly", "--standalone", "--agree-tos", "--email", "info@coopdevs.org", "--noninteractive", "-d", "staging.katuma.org"], "failed": true, "delta": "0:00:05.981783", "stderr": "Saving debug log to /var/log/letsencrypt/letsencrypt.log\\nPlugins selected: Authenticator standalone, Installer None\\nCert is due for renewal, auto-renewing...\\nRenewing an existing certificate\\nPerforming the following challenges:\\nhttp-01 challenge for staging.katuma.org\\nCleaning up challenges\\nProblem binding to port 80: Could not bind to IPv4 or IPv6.", "rc": 1, "invocation": {"module_args": {"warn": true, "executable": null, "_uses_shell": false, "_raw_params": "/opt/certbot/certbot-auto certonly --standalone --agree-tos --email info@coopdevs.org --noninteractive -d staging.katuma.org", "removes": null, "creates": null, "chdir": null, "stdin": null}}, "start": "2018-01-12 11:03:09.716910", "msg": "non-zero return code"}\r\n', 'Shared connection to 212.47.234.234 closed.\r\n')
fatal: [staging.katuma.org]: FAILED! => {
    "changed": true, 
    "cmd": [
        "/opt/certbot/certbot-auto", 
        "certonly", 
        "--standalone", 
        "--agree-tos", 
        "--email", 
        "info@coopdevs.org", 
        "--noninteractive", 
        "-d", 
        "staging.katuma.org"
    ], 
    "delta": "0:00:05.981783", 
    "end": "2018-01-12 11:03:15.698693", 
    "invocation": {
        "module_args": {
            "_raw_params": "/opt/certbot/certbot-auto certonly --standalone --agree-tos --email info@coopdevs.org --noninteractive -d staging.katuma.org", 
            "_uses_shell": false, 
            "chdir": null, 
            "creates": null, 
            "executable": null, 
            "removes": null, 
            "stdin": null, 
            "warn": true
        }
    }, 
    "msg": "non-zero return code", 
    "rc": 1, 
    "start": "2018-01-12 11:03:09.716910", 
    "stderr": "Saving debug log to /var/log/letsencrypt/letsencrypt.log\nPlugins selected: Authenticator standalone, Installer None\nCert is due for renewal, auto-renewing...\nRenewing an existing certificate\nPerforming the following challenges:\nhttp-01 challenge for staging.katuma.org\nCleaning up challenges\nProblem binding to port 80: Could not bind to IPv4 or IPv6.", 
    "stderr_lines": [
        "Saving debug log to /var/log/letsencrypt/letsencrypt.log", 
        "Plugins selected: Authenticator standalone, Installer None", 
        "Cert is due for renewal, auto-renewing...", 
        "Renewing an existing certificate", 
        "Performing the following challenges:", 
        "http-01 challenge for staging.katuma.org", 
        "Cleaning up challenges", 
        "Problem binding to port 80: Could not bind to IPv4 or IPv6."
    ], 
    "stdout": "Requesting to rerun /opt/certbot/certbot-auto with root privileges...", 
    "stdout_lines": [
        "Requesting to rerun /opt/certbot/certbot-auto with root privileges..."
    ]
}
```

**Comment by elf-pavlik** [comment]
I just hit this one on a fresh server and in `/var/log/letsencrypt/letsencrypt.log` I see:
```
FailedChallenges: Failed authorization procedure. cornucopia.hackers4peace.net (http-01): 
urn:acme:error:unauthorized :: The client lacks sufficient authorization ::
 Invalid response from http://cornucopia.hackers4peace.net/.well-known/acme-challenge/4A45Fq5Tn7RuJB13piA0plrlf5sB8EhYWeupK4-LfiY [5.9.161.176]: 503
```

It seems that can't bind to port 80

adding `become: yes` to https://github.com/openfoodfoundation/ofn-install/blob/master/playbooks/provision.yml#L56 doesn't help 😞

**Comment by elf-pavlik** [comment]
I fiddled with it quite a bit and it seems like certbot standalone doesn't work properly (tested by running the  command from `cert` role manually). If instead I `cd /tmp` and run `python -m SimpleHTTPServer 80` I can get cert by replacing in certbot-auto `--standalone` with `--webroot -w /tmp`.
I'll try to report it directly to certbot issues tracker.

**Comment by elf-pavlik** [comment]
I think #124 fixed it

**Comment by enricostano** [comment]
Maybe, let's close it for now and open again if the issue appears again. Thanks for the headsup @elf-pavlik
