### ISSUE TITLE
Fix domain validation with TLS-SNI-01 with certbot

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/ofn-install#324]
## Description

All instance must have received an email from Let's Encrypt with the following content

Hello,
**Action is required to prevent your Let's Encrypt certificate renewals from breaking.**
Your Let’s Encrypt client used ACME TLS-SNI-01 domain validation to issue a certificate in the past 60 days.
TLS-SNI-01 validation is reaching end-of-life and will stop working on **February 13th, 2019.**
You need to update your ACME client to use an alternative validation method (HTTP-01, DNS-01 or TLS-ALPN-01) before this date or your certificate renewals will break and existing certificates will start to expire.
If you need help updating your ACME client, please open a new topic in the Help category of the Let's Encrypt community forum:
 https://community.letsencrypt.org/c/help
Please answer all of the questions in the topic template so we can help you.
For more information about the TLS-SNI-01 end-of-life please see our API announcement:
https://community.letsencrypt.org/t/february-13-2019-end-of-life-for-all-tls-sni-01-validation-support/74209
Thank you,
 Let's Encrypt Staff

It's quite self-explanatory. In order for our servers to keep working we need to follow the steps outlined in https://community.letsencrypt.org/t/how-to-stop-using-tls-sni-01-with-certbot/83210.

## Tasks

- [x] This means updating `certbot_nginx` to 0.0.3
- [x] provision all machines
- [x] run the command stated in the post above.

Here come the steps I took. Make sure you are install the latest plugins specified in `bin/requirements.txt`:

1. Provision the server with `ansible-playbook playbooks/provision.yml --limit=<host> --tags=certbot`. Note secrets can be skipped here.
2. Log in as `ofn-admin` and check `certbot --version` returns `certbot 0.28.0` (it returned certbot 0.26.1 before)
3. Run `sudo sh -c "sed -i.bak -e 's/^\(pref_challs.*\)tls-sni-01\(.*\)/\1http-01\2/g' /etc/letsencrypt/renewal/*; rm -f /etc/letsencrypt/renewal/*.bak"`
4. Run `sudo certbot renew --dry-run`
5. Check the output of the command above is something like

```
Congratulations, all renewals succeeded. The following certs have been renewed:
  /etc/letsencrypt/live/staging.katuma.org/fullchain.pem (success)
```

## Fixed servers

- [x] Katuma staging
- [x] Katuma production
- [x] UK staging
- [x] UK production
- [x] FR staging
- [x] FR production
- [x] BE production
- [x] Skandinavia production
- [x] AUS production
- [x] AUS staging
- [x] US production
- [x] CAN production
- [x] DE production

**Comment by sauloperez** [comment]
This is very urgent

> TLS-SNI-01 validation is reaching end-of-life and will stop working on **February 13th, 2019.**

**Comment by sauloperez** [comment]
@pacodelaluna I had some issues on French staging that may cause problems when the certs get autorenewed. Check the output in [certbot_renew_dry_run_off_output.log](https://github.com/openfoodfoundation/ofn-install/files/2894983/certbot_renew_dry_run_off_output.log)

**Comment by sauloperez** [comment]
@Matt-Yorkley @lin-d-hop it went well with UK production but there was a warning worth investigating. Check 
[certbot_renew_dry_run_ofn_uk_output.log](https://github.com/openfoodfoundation/ofn-install/files/2895013/certbot_renew_dry_run_ofn_uk_output.log). Where does that deploy hook come from? something that needs cleanup?

**Comment by sauloperez** [comment]
Skandinavia, AUS, US and CAN are still left. I've never touched these and I have little confidence. I even checked `certbot --version` in AUS production and I got `certbot: command not found`. Could you @mkllnk  lend me a hand so that I do it myself? We still depend too much on your for these servers.

**Comment by mkllnk** [comment]
Here is what I posted on Slack earlier:

Australia

- Certbot used to be installed in `/opt` and uses the root user's crontab to check the cert validity once a day.
- As root: `crontab -l` shows you exactly where the binary is.
- Upgrading should happen when using this command: `/opt/certbot/certbot-auto renew`

Canada:

- The Canadian server has the cron config in `/etc/cron.daily/certbot`.
- The binary is `/root/bin/certbot-auto renew`.

**Comment by mkllnk** [comment]
Aus staging is like any other ofn-install server.

**Comment by sauloperez** [comment]
So, for the 3 remaining servers, AUS, CAN and Skandinavia production, how do you provision them @mkllnk ?

**Comment by mkllnk** [comment]
For this task we just need to update certbot. We just need to call the binary and it will update itself. The other option would be run only the certbot part of ofn-install provisioning and remove the old certbot installation. The config under /etc/letsencrypt should persist and everything should be fine. This approach would make the servers a bit more compatible with ofn-install. Would you like to do that or should I have a go?

**Comment by sauloperez** [comment]
I was trying to understand if these servers have some sort of config management or are manually configured a la wild west.

**Comment by sigmundpetersen** [comment]
@sauloperez re. Scandinavia:
- You should have access
- not on ofn-install yet
- No issues with certbot

🙂

**Comment by sauloperez** [comment]
Thanks @sigmundpetersen ! Norway has `0.31.0` and `--dry-run` reports no errors :+1:

**Comment by mkllnk** [comment]
I just added Germany to the list which needs fixing as well. I tried to do it didn't work:

```
$ ansible-playbook playbooks/provision.yml --limit=openfoodnetwork.de --tags=certbot
openfoodnetwork.de         : ok=5    changed=0    unreachable=0    failed=0

$ ssh openfoodnetwork.de "sudo certbot --version"
certbot 0.21.1
# This is not 0.28 or newer!
```

Since I was already logged in, I ran `apt upgrade certbot` myself and that upgraded successfully. I also ran the other commands but it all looks fine. But the renewal config actually didn't specify a protocol and it's still using http-01 as standard (not TLS-SNI-01). I guess that's the same on other servers. So I'm wondering if we were actually affected by this upgrade.

**Comment by sauloperez** [comment]
> I also ran the other commands but it all looks fine.

does this mean step 3 as well?

**Comment by mkllnk** [comment]
Yes, I did step 3 but the sed command didn't have any effect because there was no string `tls-sni-01` in the configs. I just checked Katuma and there is no `http-01` in the config which means that we didn't need the sed command. Anyway, maybe one of our servers is out of line and did need that command. It doesn't hurt. It's good to apply it anyway.

**Comment by mkllnk** [comment]
I fixed Canada, closing this issue.

**Comment by sauloperez** [comment]
any chance to know how and have it documented?

**Comment by mkllnk** [comment]
I ran `/root/bin/certbot-auto --version` which auto-upgraded certbot. I looked into the renewal config but there was nothing to update (sed command having no effect). I would like to re-install that server soon.
