### ISSUE TITLE
Unicorn tuning

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/ofn-install#385]
Much like our default Postgres configuration, it looks like there are some Unicorn tuning options we could look at that are recommended for running Rails on production servers.

The main ones are:

- [x] Set `worker_processes` to around 3-4 (we're trialling this in UK and AUS). 
- [x] Use the `preload_app` feature. It seems to be universally recommended for speeding up production environments, and enables ruby's copy-on-write features.
- [x] Use the `unicorn-worker-killer` gem to automatically clean up worker processes between requests to reduce issues from memory leaks.

Notes:
https://devcenter.heroku.com/articles/rails-unicorn
https://blog.codeship.com/heroku-unicorn/
https://docs.gitlab.com/ee/administration/operations/unicorn.html
https://www.digitalocean.com/community/tutorials/how-to-optimize-unicorn-workers-in-a-ruby-on-rails-app

**Comment by sauloperez** [comment]
I used `unicorn-worker-killer` in the past and that helped mem usage of unicorns to be consistent. I'd like however to check first whether this is a problem for us. #datadriven

**Comment by mkllnk** [comment]
`preload_app` sounds like an excellent idea. That should save some memory.

I wouldn't go for the unicorn-worker-killer though because we don't have any memory leaks. We used to achieve a similar thing with monit which would kill workers when they ran over a memory limit but that was a pain. The configuration needs adjusting regularly.

A long-running unicorn worker occupies more memory than a freshly started one. But that is because it cached a few things which makes it faster to respond. Restarting wipes out that advantage and is additional load on the server.

The memory usage of our workers grows initially but then stays stable:
![Screenshot from 2019-07-18 11-20-18](https://user-images.githubusercontent.com/3524483/61422245-34ce7680-a94e-11e9-907e-326b58517e9e.png)

The dips are unicorn restarts. There is a clear upper limit to the memory usage (= no leak). The big drop is reducing our workers from 6 to 3 because of the concurrent checkout issue.

**Comment by sauloperez** [comment]
so then we can focus or more cost-effective things than `unicorn-worker-killer`.

**Comment by Matt-Yorkley** [comment]
Sounds good. I'll leave this issue open for implementing `preload_app` then.

**Comment by sauloperez** [comment]
Wouldn't it be better to create a separate issue for it with the required details of what needs to be done?

**Comment by Matt-Yorkley** [comment]
If we start using `preload_app` then we might get more mileage out of using `unicorn-worker-killer`...?

**Comment by mkllnk** [comment]
I still think that `unicorn-worker-killer` is a band-aid that we don't need at the moment (no memory leak). Why do you want to use it?

**Comment by sauloperez** [comment]
@Matt-Yorkley might be right since I doubt the mem. will be freed when reloading. 

Also, whether there's mem leak or not can be checked in our metrics. I suspect we have some at least due to some old gems.
