### ISSUE TITLE
Set up CI for ofn-install

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/ofn-install#414]
I think this is long overdue. We don't have to do it all at once, but here's what I would suggest:

- [x]  Add a basic CI build that runs though `site.yml` #418 
- [x]  Test other core playbooks #421 
- [x]  Add some actual tests to the process! We can do it really easily with Ansible #421 
- [ ] Use the "test" certificates feature with Certbot so we can check it's working (it broke recently: https://github.com/openfoodfoundation/ofn-install/issues/392) 

Maybe we can take a look at this at the UK devhack?
